### ISSUE TITLE
Removing iron 

### ISSUE THREAD

**Issue by hkupty** [languitar/config-vim#1]
Hi, I'm Henry and I'm the creator and maintainer of iron.

First of all, I'm sorry for opening an issue on your dotfiles but github doesn't provide me with better tools to communicate.

Since you wrote an article about iron.nvim, let me start by thanking you.

I checked your dotfiles and I noticed that you removed iron as a dependency recently. 

I'm curious if I could have decreased the quality of iron on the process of migrating it to lua and if that caused you to stop using it.

Please don't take this as if I am trying to force you to use it and excuse me if you feel that I am being invasive by asking you.

I just feel that, since you wrote a nice article that even today consistently brings traffic to iron, it'd be a pity if you get frustrated with it to the point of stop using it.

Best regards,
Henry

**Comment by languitar** [comment]
hi, there was one particular issue where `cl` seems to be mapped in iron, which I use sometimes. I didn't investigate much into avoiding this mapping since I don't need such a file-based REPL workflow a lot right now. That's the reason for removing iron right now. But if you have a solution for avoiding mapping `cl`, I'd be interested in that.

**Comment by hkupty** [comment]
I'll look into it.

I don't want my plugins to be invasive and get in the way. Pretty much the contrary, as I want them to increase productivity, not to bother people.
